package stringsearch;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
        
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author smlle
 */
public class janelaPrincipal extends javax.swing.JFrame {

    private final Kmp searchKmp;
    private final Naive searchNaive;
    private final RabinKarp searchRabinKarp;
    private final BoyerMoore searchBoyerMoore;
    private final AhoCorasick searchAhoCorasick;
    private final Log logr; 
    /**
     * Creates new form NewJFrame
     */
    public janelaPrincipal() throws IOException {
        this.searchKmp = new Kmp();
        this.searchNaive = new Naive();
        this.searchRabinKarp = new RabinKarp();
        this.searchBoyerMoore = new BoyerMoore();
        this.searchAhoCorasick = new AhoCorasick();
        this.logr=new Log();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pesquisaPalavra = new javax.swing.JTextField();
        nomeArquivoLabel = new javax.swing.JLabel();
        Naive = new javax.swing.JButton();
        RabinKarp = new javax.swing.JButton();
        KMP = new javax.swing.JButton();
        BoyerMoore = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nomeArquivo = new javax.swing.JTextField();
        AhoCorasick = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pesquisa");

        pesquisaPalavra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisaPalavraActionPerformed(evt);
            }
        });

        nomeArquivoLabel.setText("Nome do Arquivo");

        Naive.setText("Naive");
        Naive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NaiveActionPerformed(evt);
            }
        });

        RabinKarp.setText("RabinKarp");
        RabinKarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RabinKarpActionPerformed(evt);
            }
        });

        KMP.setText("KMP");
        KMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KMPActionPerformed(evt);
            }
        });

        BoyerMoore.setText("BoyerMoore");
        BoyerMoore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoyerMooreActionPerformed(evt);
            }
        });

        jLabel2.setText("Palavra");

        nomeArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeArquivoActionPerformed(evt);
            }
        });

        AhoCorasick.setText("AhoCorasick");
        AhoCorasick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AhoCorasickActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Naive, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeArquivoLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pesquisaPalavra, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomeArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RabinKarp, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(KMP, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BoyerMoore)
                        .addGap(12, 12, 12)
                        .addComponent(AhoCorasick)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(nomeArquivoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pesquisaPalavra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(nomeArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Naive)
                    .addComponent(RabinKarp)
                    .addComponent(KMP)
                    .addComponent(BoyerMoore)
                    .addComponent(AhoCorasick))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NaiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NaiveActionPerformed
        logr.getLog().log(Level.SEVERE, "Iniciando o Naive");
        double startTime = System.nanoTime();
        searchNaive.callAlgorithm(pesquisaPalavra.getText(),nomeArquivo.getText(),logr);
        double endTime   = System.nanoTime(); 
        double totalTime = (endTime - startTime)/ 1000000000.0;
        JOptionPane.showMessageDialog(null, "Tempo de execução Naive "+totalTime+" segundos");
    }//GEN-LAST:event_NaiveActionPerformed

    private void RabinKarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RabinKarpActionPerformed
        logr.getLog().log(Level.SEVERE, "Iniciando o Rabin");
        double startTime = System.nanoTime();
        searchRabinKarp.callAlgorithm(pesquisaPalavra.getText(),nomeArquivo.getText(),logr);
        double endTime   = System.nanoTime();
        double totalTime = (endTime - startTime)/ 1000000000.0;
        JOptionPane.showMessageDialog(null, "Tempo de execução do Rabin "+totalTime+" segundos");
    }//GEN-LAST:event_RabinKarpActionPerformed

    private void KMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KMPActionPerformed
        logr.getLog().log(Level.SEVERE, "Iniciando o KMP");
        double startTime = System.nanoTime();
        searchKmp.callAlgorithm(pesquisaPalavra.getText(),nomeArquivo.getText(),logr);
        double endTime   = System.nanoTime();
        double totalTime = (endTime - startTime)/ 1000000000.0;
        JOptionPane.showMessageDialog(null, "Tempo de execução do KMP "+totalTime+" segundos");
    }//GEN-LAST:event_KMPActionPerformed

    private void BoyerMooreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoyerMooreActionPerformed
        logr.getLog().log(Level.SEVERE, "Iniciando o Boyer");
        double startTime = System.nanoTime();
        searchBoyerMoore.callAlgorithm(pesquisaPalavra.getText(),nomeArquivo.getText(),logr);
        double endTime   = System.nanoTime();
        double totalTime = (endTime - startTime)/ 1000000000.0;
        JOptionPane.showMessageDialog(null, "Tempo de execução do Boyer "+totalTime+" segundos");
    }//GEN-LAST:event_BoyerMooreActionPerformed
 
    private void pesquisaPalavraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisaPalavraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisaPalavraActionPerformed

    private void nomeArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeArquivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeArquivoActionPerformed

    private void AhoCorasickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AhoCorasickActionPerformed
        logr.getLog().log(Level.SEVERE, "Iniciando o Aho");
        double startTime = System.nanoTime();
        searchNaive.callAlgorithm(pesquisaPalavra.getText(),nomeArquivo.getText(),logr);
        double endTime   = System.nanoTime();
        double totalTime = (endTime - startTime)/ 1000000000.0;
        JOptionPane.showMessageDialog(null, "Tempo de execução Aho Corasick "+totalTime+" segundos");
    }//GEN-LAST:event_AhoCorasickActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(janelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(janelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(janelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(janelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new janelaPrincipal().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(janelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AhoCorasick;
    private javax.swing.JButton BoyerMoore;
    private javax.swing.JButton KMP;
    private javax.swing.JButton Naive;
    private javax.swing.JButton RabinKarp;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField nomeArquivo;
    private javax.swing.JLabel nomeArquivoLabel;
    private javax.swing.JTextField pesquisaPalavra;
    // End of variables declaration//GEN-END:variables
}
